version: "3"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    stdin_open: true
    volumes:
      - odoo-odoo14-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./bloopark-addons:/mnt/extra-addons
    restart: always # run as a service
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5542:5432"
    restart: always # run as a service
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@bloopark.de
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8099:80"
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:psql-ronba-server"
volumes:
  odoo-odoo14-data:
  odoo-db-data:
  pgadmin-data:
